---
ReportDefinitions:
  - reportName: ReceiptRegisterSW_test
    summary: Receipt Register Test
    version: 1.0.0
    moduleName: rainmaker-at
    sourceColumns:
    - name: receiptnumber
      label: receiptNo
      type: string
      source: at
      total: false
    - name: transactiondate
      label: receiptDate
      type: string
      source: at
      total: false
    - name: g8issuedate
      label: g8issuedate
      type: string
      source: at
      total: false
    - name: g8receiptno
      label: g8receiptno
      type: string
      source: at
      total: false
    searchParams:
    - name: fromDate
      label: fromDate
      type: epoch
      source: at
      isMandatory: false
      searchClause: AND rh.receiptdate >= $fromDate
    - name: toDate
      label: toDate
      type: epoch
      source: at
      isMandatory: false
      searchClause: AND rh.receiptdate <= $toDate
    query: |
      -- Use CTE to force query plan, compute & use CTE later
      WITH receipt_breakup AS (
                  SELECT 
                    receiptheader, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_ADHOC_PENALTY' THEN adjustedamount ELSE 0 END) as adhocpenalty, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_ADHOC_PENALTY' THEN adjustedamount ELSE 0 END) as adhocrebate, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_FIRE_CESS' THEN adjustedamount ELSE 0 END) as firecess, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_CANCER_CESS' THEN adjustedamount ELSE 0 END) as cancercess, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_TIME_INTEREST' THEN adjustedamount ELSE 0 END) as interest, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_TIME_PENALTY' THEN adjustedamount ELSE 0 END) as penalty, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_TIME_REBATE' THEN adjustedamount ELSE 0 END) as rebate, 
                    (SUM(CASE WHEN taxheadcode LIKE 'PT_TAX' THEN adjustedamount ELSE 0 END) 
                    + SUM(CASE WHEN taxheadcode LIKE 'PT_DECIMAL_CEILING_DEBIT' THEN adjustedamount ELSE 0 END)) 
                    as propertytax, 
                    SUM(CASE WHEN taxheadcode LIKE 'PT_UNIT_USAGE_EXEMPTION' THEN adjustedamount ELSE 0 END) as exemption, 
                    (SUM(CASE WHEN taxheadcode LIKE 'PT_DECIMAL_CEILING_CREDIT' THEN adjustedamount ELSE 0 END)
                    + SUM(CASE WHEN taxheadcode LIKE 'PT_DECIMAL_CEILING_DEBIT' THEN adjustedamount ELSE 0 END))  as adjusment
                  FROM egcl_receiptdetails_v1
                  WHERE tenantid LIKE $tenantid
                  GROUP BY receiptheader
      )
      SELECT 
        rh.tenantid AS tenantid, 
        rh.id, 
        Substring(rh.consumercode, '(.*):') AS propertyid, 
        Substring(rh.consumercode, ':(.*)') AS assessmentnumber, 
        rh.consumercode, 
        rh.receiptdate, 
        To_char(To_timestamp(rh.receiptdate / 1000), 'DD/MM/YYYY') AS transactiondate, 
        bankid AS bankname, 
        receiptnumber, 
        amount, 
        instrumenttype, 
        transactionnumber, 
        receipt_breakup.*, 
        rh.totalamount - ih.amount AS pendingamount,
        pt_detail.financialyear,
        To_char(To_timestamp(rh.manualreceiptdate / 1000), 'DD/MM/YYYY') AS g8issuedate,
        Initcap(COALESCE(pt_detail.usagecategoryminor, pt_detail.usagecategorymajor)) as usagetype,
        manualreceiptnumber as g8receiptno
      FROM egcl_receiptheader_v1 AS rh
      JOIN egcl_receiptinstrument_v1 AS ri ON rh.id = ri.receiptheader
      JOIN egcl_instrumentheader_v1 AS ih ON ih.id = ri.instrumentheader
      JOIN receipt_breakup ON rh.id = receipt_breakup.receiptheader
      JOIN eg_pt_propertydetail_v2 pt_detail ON CONCAT(pt_detail.property, ':', pt_detail.assessmentnumber) = rh.consumercode
      JOIN eg_pt_address_v2 pt_addr ON pt_detail.property = pt_addr.property
      WHERE rh.tenantid LIKE $tenantid and rh.status != 'Cancelled'
    orderby: ORDER BY rh.receiptdate DESC
