---
ReportDefinitions:
  - reportName: StateReceiptRegisterGarbage
    decryptionPathId: GARBAGEREPORTS
    summary: Details of collector register in garbage collection service
    version: 1.0.0
    moduleName: rainmaker-gc
    additionalConfig:
      print:
        pdfPageSize: A4
    sourceColumns:
      - name: tenant
        label: ULB Name
        type: string
        source: gc
        total: false
      - name: receiptno
        label: Receipt Number
        type: string
        source: gc
        total: false
      - name: applicationno
        label: Application Number
        type: string
        source: gc
        total: false
      - name: receiptdate1
        label: Receipt Date
        type: string
        source: gc
        total: false
      - name: service
        label: Service
        type: string
        source: gc
        total: false
      - name: transactiondate
        label: Transaction Date
        type: string
        source: gc
        total: false
      - name: transaction_id
        label: Transaction Id
        type: string
        source: gc
        total: false
      - name: amountpaid
        label: Amount Paid
        type: string
        source: gc
        total: true
      - name: paymentmode
        label: Payment Mode
        type: string
        source: gc
        total: false
    searchParams:
      - name: fromDate
        label: From Date
        type: epoch
        source: gc
        isMandatory: true
        searchClause: AND pd.receiptdate >= $fromDate
      - name: toDate
        label: To Date
        type: epoch
        source: gc
        isMandatory: true
        searchClause: AND pd.receiptdate <= $toDate
      - name: receiptNumber
        label: Receipt Number
        type: string
        source: gc
        isMandatory: false
        searchClause: AND pd.receiptnumber like $receiptNumber
      - name: paymentMode
        label: Payment Mode
        type: singlevaluelist
        pattern: list://CASH:CASH,CHEQUE:CHEQUE,DD:DD,ONLINE:ONLINE,CARD:CARD,OFFLINE_NEFT:OFFLINE NEFT
        source: gc
        isMandatory: false
        searchClause: AND payment.paymentmode like $paymentMode
      - name: ulb
        label: ULB Name
        type: singlevaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: gc
        isMandatory: false
        searchClause: AND pd.tenantid = $ulb
    query: >
      SELECT 
                pd.receiptnumber AS receiptno,
                bill.consumercode AS applicationno,
                INITCAP(split_part(pd.tenantid, '.', 2)) AS tenant,
                TO_CHAR(
                    TO_TIMESTAMP(pd.receiptdate / 1000) AT TIME ZONE 'Asia/Kolkata',
                    'DD-MM-YYYY'
                ) AS receiptdate,
                --pd.businessservice ,
                'Garbage Collection' AS service,
                TO_CHAR(
                    TO_TIMESTAMP(payment.instrumentdate / 1000) AT TIME ZONE 'Asia/Kolkata',
                    'DD-MM-YYYY'
                ) AS transactiondate,
                payment.instrumentnumber AS transaction_id,
                usr.name AS ownername1,
                pd.amountpaid,pd.due,
                payment.paymentmode,
                payment.paymentstatus
            FROM egcl_paymentdetail pd
            INNER JOIN egcl_bill bill   ON bill.id = pd.billid 
            INNER JOIN egcl_payment payment   ON payment.id = pd.paymentid
            LEFT JOIN eg_gc_connection a   ON bill.consumercode = a.applicationno
            LEFT JOIN eg_user usr   ON usr.id = payment.createdby::integer
            WHERE
                pd.businessservice in ('GC.ONE_TIME_FEE')
                AND payment.paymentstatus != 'CANCELLED' and pd.tenantid = $tenantid
    orderby: ORDER BY pd.receiptdate DESC

  - reportName: ReceiptRegisterGarbage
    decryptionPathId: GARBAGEREPORTS
    summary: Details of collector register in garbage collection service
    version: 1.0.0
    moduleName: rainmaker-gc
    additionalConfig:
      print:
        pdfPageSize: A4
    sourceColumns:
      - name: tenant
        label: ULB Name
        type: string
        source: gc
        total: false
      - name: receiptno
        label: Receipt Number
        type: string
        source: gc
        total: false
      - name: applicationno
        label: Application Number
        type: string
        source: gc
        total: false
      - name: receiptdate1
        label: Receipt Date
        type: string
        source: gc
        total: false
      - name: service
        label: Service
        type: string
        source: gc
        total: false
      - name: transactiondate
        label: Transaction Date
        type: string
        source: gc
        total: false
      - name: transaction_id
        label: Transaction Id
        type: string
        source: gc
        total: false
      - name: amountpaid
        label: Amount Paid
        type: string
        source: gc
        total: true
      - name: paymentmode
        label: Payment Mode
        type: string
        source: gc
        total: false
    searchParams:
      - name: fromDate
        label: From Date
        type: epoch
        source: gc
        isMandatory: true
        searchClause: AND pd.receiptdate >= $fromDate
      - name: toDate
        label: To Date
        type: epoch
        source: gc
        isMandatory: true
        searchClause: AND pd.receiptdate <= $toDate
      - name: receiptNumber
        label: Receipt Number
        type: string
        source: gc
        isMandatory: false
        searchClause: AND pd.receiptnumber like $receiptNumber
      - name: paymentMode
        label: Payment Mode
        type: singlevaluelist
        pattern: list://CASH:CASH,CHEQUE:CHEQUE,DD:DD,ONLINE:ONLINE,CARD:CARD,OFFLINE_NEFT:OFFLINE NEFT
        source: gc
        isMandatory: false
        searchClause: AND payment.paymentmode like $paymentMode
    query: >
      SELECT 
                pd.receiptnumber AS receiptno,
                bill.consumercode AS applicationno,
                INITCAP(split_part(pd.tenantid, '.', 2)) AS tenant,
                TO_CHAR(
                    TO_TIMESTAMP(pd.receiptdate / 1000) AT TIME ZONE 'Asia/Kolkata',
                    'DD-MM-YYYY'
                ) AS receiptdate,
                --pd.businessservice ,
                'Garbage Collection' AS service,
                TO_CHAR(
                    TO_TIMESTAMP(payment.instrumentdate / 1000) AT TIME ZONE 'Asia/Kolkata',
                    'DD-MM-YYYY'
                ) AS transactiondate,
                payment.instrumentnumber AS transaction_id,
                usr.name AS ownername1,
                pd.amountpaid,pd.due,
                payment.paymentmode,
                payment.paymentstatus
            FROM egcl_paymentdetail pd
            INNER JOIN egcl_bill bill   ON bill.id = pd.billid 
            INNER JOIN egcl_payment payment   ON payment.id = pd.paymentid
            LEFT JOIN eg_gc_connection a   ON bill.consumercode = a.applicationno
            LEFT JOIN eg_user usr   ON usr.id = payment.createdby::integer
            WHERE
                pd.businessservice in ('GC.ONE_TIME_FEE')
                AND payment.paymentstatus != 'CANCELLED' and pd.tenantid != 'pb.testing'
    orderby: ORDER BY pd.receiptdate DESC
