---
ReportDefinitions:
  - reportName: ApplicationDetailReport
    decryptionPathId: 
    summary: Details of applicant in ndc service
    version: 1.0.0
    moduleName: rainmaker-ndc
    additionalConfig:
      print:
        pdfPageSize: A1
    sourceColumns:
      - name: name
        label: reports.ndc.name
        type: string
        source: ndc
        total: false
      - name: mobilenumber
        label: reports.ndc.mobilenumber
        type: string
        source: ndc
        total: false
      - name: emailid
        label: reports.ndc.emailid
        type: string
        source: ndc
        total: false
      - name: tenantid
        label: reports.ndc.tenantid
        type: string
        source: ndc
        total: false
      - name: address
        label: reports.ndc.address
        type: string
        source: ndc
        total: false
      - name: action
        label: reports.ndc.action
        type: string
        source: ndc
        total: false
      - name: consumercode
        label: reports.ndc.consumercode
        type: string
        source: ndc
        total: false
      - name: applicationstatus
        label: reports.ndc.applicationstatus
        type: string
        source: ndc
        total: false
      - name: businessservice
        label: reports.ndc.businessservice
        type: string
        source: ndc
        total: false
      - name: dueamount
        label: reports.ndc.dueamount
        type: string
        source: ndc
        total: true
      - name: applicationid
        label: reports.ndc.applicationid
        type: string
        source: ndc
        total: false
      - name: status
        label: reports.ndc.status
        type: string
        source: ndc
        total: false
      - name: status
        label: reports.ndc.status
        type: string
        source: ndc
        total: false
    searchParams:
      - name: fromDate
        label: reports.ndc.fromDate
        type: epoch
        source: ndc
        isMandatory: true
        searchClause: AND a.createdtime >= $fromDate
      - name: toDate
        label: reports.ndc.toDate
        type: epoch
        source: ndc
        isMandatory: true
        searchClause: AND a.createdtime <= $toDate
      - name: tenantid
        label: reports.ndc.tenantid
        type: string
        source: ndc
        isMandatory: false
        searchClause: AND a.tenantid = $tenantid
    query: >
      -- Use CTE to force query plan, compute & use CTE later
      SELECT 
        u.name, u.mobilenumber, u.emailid ,ua.address,a.tenantid,
        a.action, d.consumercode, a.applicationstatus, d.businessservice, 
        d.applicationid, d.dueamount, d.status
      FROM eg_user u
        JOIN eg_ndc_owner o ON u.uuid = o.uuid
        JOIN eg_ndc_details d  ON o.ndcapplicationuuid = d.applicationid
        JOIN eg_ndc_application a ON a.uuid = o.ndcapplicationuuid
        LEFT JOIN eg_user_address ua ON ua.userid = u.id
        WHERE a.tenantid = $tenantid
  - reportName: CollectionsReport
    summary: Collections
    version: 1.0.0
    moduleName: rainmaker-ndc
    additionalConfig:
      print:
        pdfPageSize: A1
    sourceColumns:
      - name: month
        label: reports.ndc.month
        type: string
        source: ndc
        total: false
      - name: totalamount
        label: reports.pt.totalamount
        type: string
        source: ndc
        total: false
      - name: totalcount
        label: reports.ndc.totalcount
        type: string
        source: ndc
        total: false
      - name: online
        label: reports.ndc.online
        type: string
        source: ndc
        total: true
      - name: cash
        label: reports.ndc.cash
        type: string
        source: ndc
        total: true
      - name: cheque
        label: reports.ndc.cheque
        type: string
        source: ndc
        total: true
      - name: dd
        label: reports.ndc.dd
        type: string
        source: ndc
        total: true
      - name: card
        label: reports.ndc.card
        type: string
        source: ndc
        total: true
      - name: neft
        label: reports.ndc.neft
        type: string
        source: ndc
        total: true
      - name: rtgs
        label: reports.ndc.rtgs
        type: string
        source: ndc
        total: true
      - name: po
        label: reports.ndc.po
        type: string
        source: ndc
        total: true
    searchParams:
      - name: tenantid
        label: reports.ndc.tenantid
        type: string
        source: ndc
        isMandatory: false
        searchClause: AND payment.tenantid = $tenantid
      - name: businessservice
        label: reports.ndc.businessservice
        type: string
        source: ndc
        isMandatory: true
        searchClause: AND pd.businessservice = $businessservice
    query: >
      -- Use CTE to force query plan, compute & use CTE later

      SELECT 
      DATE_TRUNC('month', TO_TIMESTAMP(payment.createdtime / 1000) AT TIME ZONE 'Asia/Kolkata') AS month,
      SUM(payment.totalamountpaid) AS totalamount,
      COUNT(payment.totalamountpaid) AS totalcount,
      SUM(CASE WHEN payment.paymentmode = 'ONLINE' THEN payment.totalamountpaid ELSE 0 END) AS online,
      SUM(CASE WHEN payment.paymentmode = 'CASH' THEN payment.totalamountpaid ELSE 0 END) AS cash,
      SUM(CASE WHEN payment.paymentmode = 'CHEQUE' THEN payment.totalamountpaid ELSE 0 END) AS cheque,
      SUM(CASE WHEN payment.paymentmode = 'DD' THEN payment.totalamountpaid ELSE 0 END) AS dd,
      SUM(CASE WHEN payment.paymentmode = 'CARD' THEN payment.totalamountpaid ELSE 0 END) AS card,
      SUM(CASE WHEN payment.paymentmode = 'OFFLINE_RTGS' THEN payment.totalamountpaid ELSE 0 END) AS rtgs,
      SUM(CASE WHEN payment.paymentmode = 'OFFLINE_NEFT' THEN payment.totalamountpaid ELSE 0 END) AS neft,
      SUM(CASE WHEN payment.paymentmode = 'POTAL_ORDER' THEN payment.totalamountpaid ELSE 0 END) AS po
      FROM 
      egcl_paymentdetail pd
      JOIN 
      egcl_payment payment ON pd.paymentid = payment.id
      JOIN 
      egcl_bill bill ON bill.id = pd.billid
      JOIN 
      eg_ndc_details ndc ON ndc.consumercode = bill.consumercode
      WHERE 
      payment.paymentstatus != 'CANCELLED'
      AND payment.tenantid = $tenantid  
      AND pd.businessservice = $businessservice       
    groupby: DATE_TRUNC('month', TO_TIMESTAMP(payment.createdtime / 1000) AT TIME ZONE 'Asia/Kolkata')
    orderby: ORDER BY month
