ReportDefinitions:
- reportName: ApplicationDetailReport
  decryptionPathId: CITIZEN
  summary: Details of applicant in ndc service
  version: 1.0.0
  moduleName: rainmaker-ndc
  additionalConfig:
    print:
      pdfPageSize: A1
  sourceColumns:
  - name: name
    label: name
    type: string
    source: ndc
    total: false
  - name: mobilenumber
    label: mobilenumber
    type: string
    source: ndc
    total: false
  - name: emailid
    label: emailid
    type: string
    source: ndc
    total: false
  - name: tenantid
    label: tenantid
    type: string
    source: ndc
    total: false
  - name: address
    label: address
    type: string
    source: ndc
    total: false
  - name: action
    label: action
    type: string
    source: ndc
    total: false
  - name: consumercode
    label: consumercode
    type: string
    source: ndc
    total: false
  - name: applicationstatus
    label: applicationstatus
    type: string
    source: ndc
    total: false
  - name: businessservice
    label: businessservice
    type: string
    source: ndc
    total: false
  - name: dueamount
    label: dueamount
    type: string
    source: ndc
    total: true
  - name: applicationid
    label: applicationid
    type: string
    source: ndc
    total: false
  - name: status
    label: status
    type: string
    source: ndc
    total: false
  searchParams:
  - name: fromDate
    label: fromDate
    type: epoch
    source: ndc
    isMandatory: true
    searchClause: AND a.createdtime >= $fromDate
  - name: toDate
    label: toDate
    type: epoch
    source: ndc
    isMandatory: true
    searchClause: AND a.createdtime <= $toDate
  - name: tenantid
    label: tenantid
    type: singlevaluelist
    pattern: http://egov-hrms:8080/egov-hrms/employees/_search?tenantId=$tenantid&roles=WS_CEMP,WS_CLERK,SW_CEMP,SW_CLERK|$.Employees[*].user.id|$.Employees[*].user.name
    source: ndc
    wrapper: true
    isMandatory: false
    searchClause: AND a.tenantid = $tenantid
  query: |
    -- Use CTE to force query plan, compute & use CTE later
    SELECT 
      u.name, u.mobilenumber, u.emailid ,ua.address,a.tenantid,
      a.action, d.consumercode, a.applicationstatus, d.businessservice, 
      d.applicationid, d.dueamount, d.status
    FROM  eg_user  u
    
    JOIN eg_ndc_owner AS o ON u.uuid = o.uuid
    JOIN eg_ndc_details AS d ON o.ndcapplicationuuid = d.applicationid
    JOIN eg_ndc_application AS a ON a.uuid = o.ndcapplicationuuid
    LEFT JOIN eg_user_address AS ua ON ua.userid = u.id
    WHERE a.tenantid = $tenantid
