---
ReportDefinitions:
  - reportName: PT_Invalid_Defaulters
    summary: Data for defaulter property_id with no receipt number
    version: 1.0.0
    moduleName: rainmaker-pt
    additionalConfig:
    print:
        pdfPageSize: "A1"
    sourceColumns:
      - name: tenantid
        label: tenantid
        type: string
        source: pt
        total: false
      - name: district
        label: district
        type: string
        source: pt
        total: false
      - name: property_id
        label: property_id
        type: string
        source: pt
        total: false
    searchParams:
      - name: fromDate
        label: fromDate
        type: epoch
        source: pt
        isMandatory: false
        searchClause: AND billdate >= $fromDate
      - name: tenantid
        label: tenantid
        type: singlevaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: pt
        wrapper: true
        isMandatory: false
        searchClause: AND d.tenantid = $tenantid
    query: |
       -- Use CTE to force query plan, compute & use CTE later
       WITH defaulters AS (
       SELECT tenantid, property_id
       FROM pt_defaulter_ids
       ),
       bills_after_april AS (
       SELECT tenantid, consumercode AS property_id, billdate
       FROM egcl_bill 
       WHERE businessservice = 'PT'
          AND billdate > $fromDate
       ),
       ulb_mapped AS (
       SELECT ulb_code, district, name_of_ulb
       FROM ulb_data
       )
       SELECT 
       COALESCE(u.name_of_ulb, d.tenantid) AS tenantid,
       COALESCE(u.district, 'UNKNOWN') AS district,d.property_id
       FROM defaulters d
       LEFT JOIN bills_after_april b ON d.property_id = b.property_id AND d.tenantid = b.tenantid
       LEFT JOIN ulb_mapped u ON TRIM(LOWER(d.tenantid)) = TRIM(LOWER(u.ulb_code))
       WHERE b.property_id IS NULL 
    orderby: ORDER BY d.property_id DESC;
