ReportDefinitions:
  - reportName: PendencyReportMiscellaneous
    summary: Pendency Report Miscellaneous
    version: 1.0.0
    moduleName: rainmaker-misc
    sourceColumns:
      - name: district
        label: District
        type: string
        source: rainmaker-misc
        total: false
      - name: name_of_ulb
        label: ULB
        type: string
        source: rainmaker-misc
        total: false
      - name: type
        label: ULB Type
        type: string
        source: rainmaker-misc
        total: false
      - name: service
        label: Service
        type: string
        source: rainmaker-misc
        total: false
      - name: applicationstatus
        label: Application Status
        type: string
        source: rainmaker-misc
        total: false
      - name: applicationcount
        label: Application Count
        type: string
        source: rainmaker-misc
        total: false
    searchParams:
      - name: serviceselected
        label: serviceselected
        type: singlevaluelist
        pattern: list://TL%:TL-Renewal,SW%:SW-Service,WS%:WS-Service,FN%:FireNoc,BS%:Bill
          Amendment
        source: rainmaker-misc
        isMandatory: false
        searchClause: AND ta.servicename =$serviceselected
      - name: tenantselected
        label: tenantid
        type: singlevaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: rainmaker-misc
        wrapper: true
        isMandatory: false
        searchClause: AND ud.ulb_code =$tenantselected
    query: |
      select ud.district, ud.name_of_ulb, ud.ulb_code as tenantid, ud.type,
      'WS-Service'  as Service ,ws.applicationstatus 
      as  ApplicationStatus ,count(ws.applicationno) as applicationcount
      from eg_ws_connection ws inner join ulb_data ud on ws.tenantid = ud.ulb_code
      where ws.connectionno is null and ws.applicationstatus not IN ( 'CONNECTION_ACTIVATED',        
      'INITIATED','REJECTED','PENDING_FOR_PAYMENT','PENDING_FOR_CITIZEN_ACTION') 
      group by ws.applicationstatus, ud.district, ud.name_of_ulb, ud.type ,ud.ulb_code
      UNION
      select ud.district, ud.name_of_ulb, ud.type, ud.ulb_code as tenantid, 'SW-Service'  as servicename , ws.applicationstatus as ApplicationStatus ,count(applicationno) as applicationcount
      from eg_ws_connection ws inner join ulb_data ud on ws.tenantid = ud.ulb_code
      where ws.connectionno is null
      and ws.applicationstatus not IN ( 'CONNECTION_ACTIVATED', 'INITIATED','REJECTED','PENDING_FOR_PAYMENT','PENDING_FOR_CITIZEN_ACTION') 
      group by ws.applicationstatus , ud.district, ud.name_of_ulb, ud.type ,ud.ulb_code
      UNION
      select ud.district, ud.name_of_ulb, ud.type, ud.ulb_code as tenantid,'TL-Renewal'  as  servicename, tl.status as ApplicationStatus
      ,count(applicationnumber) as applicationcount
      from eg_tl_tradelicense  tl inner join ulb_data ud on tl.tenantid = ud.ulb_code
      where licensenumber IS NULL 
      and status  NOT IN ('INITIATED','REJECTED','PENDINGPAYMENT' , 'APPLIED','CANCELLED')
      group by applicationstatus , ud.district, ud.name_of_ulb, ud.type ,ud.ulb_code
      UNION
      SELECT ud.district, ud.name_of_ulb, ud.type, ud.ulb_code as tenantid,'FireNoc'  as servicename , detail.status,count(applicationnumber) as applicationcount
      FROM eg_fn_firenocdetail detail inner join eg_fn_firenoc noc on  detail.firenocuuid = noc.uuid 
      inner join ulb_data ud on noc.tenantid = ud.ulb_code
      WHERE  
      detail.status NOT IN ('INITIATED','CANCELLED','REJECTED','PENDINGPAYMENT','APPROVED')
      AND noc.firenocnumber IS NULL        
      group by detail.status , ud.district, ud.name_of_ulb, ud.type,ud.ulb_code          

  - reportName: department
    summary: Department Wise Pendency Report
    version: 1.0.0
    moduleName: department
    sourceColumns:
      - name: departmentID
        label: departmentID
        type: string
        source: rainmaker-misc
        total: false
      - name: departmentName
        label: departmentName
        type: string
        source: rainmaker-misc
        total: false
      - name: TotalApplicationReceived
        label: TotalApplicationReceived
        type: string
        source: rainmaker-misc
        total: false
      - name: PendingBeyondTimelineApplicationCount
        label: PendingBeyondTimelineApplicationCount
        type: string
        source: rainmaker-misc
        total: false
    query: |
        WITH ws_data AS (SELECT tenantid, applicationno, applicationstatus, createdtime, 'WS-Service' AS servicename,
        CASE WHEN EXTRACT(MONTH FROM TO_TIMESTAMP(createdtime / 1000)) >= 4 THEN TO_CHAR(TO_TIMESTAMP(createdtime / 1000), 'YYYY') || '-' ||
        RIGHT(TO_CHAR(TO_TIMESTAMP(createdtime / 1000) + INTERVAL '1 year', 'YYYY'), 2) ELSE TO_CHAR(TO_TIMESTAMP(createdtime / 1000) - INTERVAL '1 year', 'YYYY') || '-' ||
        RIGHT(TO_CHAR(TO_TIMESTAMP(createdtime / 1000), 'YYYY'), 2) END AS financialyear
        FROM eg_ws_connection WHERE connectionno IS NULL),
        sw_data AS (SELECT tenantid, applicationno, applicationstatus, createdtime,'SW-Service' AS servicename,
        CASE WHEN EXTRACT(MONTH FROM TO_TIMESTAMP(createdtime / 1000)) >= 4 THEN TO_CHAR(TO_TIMESTAMP(createdtime / 1000), 'YYYY') || '-' ||
        RIGHT(TO_CHAR(TO_TIMESTAMP(createdtime / 1000) + INTERVAL '1 year', 'YYYY'), 2) ELSE TO_CHAR(TO_TIMESTAMP(createdtime / 1000) - INTERVAL '1 year', 'YYYY') || '-' ||
        RIGHT(TO_CHAR(TO_TIMESTAMP(createdtime / 1000), 'YYYY'), 2) END AS financialyear
        FROM eg_sw_connection WHERE connectionno IS NULL),
        tl_data AS (SELECT tenantid, applicationnumber, status, createdtime,'TL-Service' AS servicename, financialyear
        FROM eg_tl_tradelicense WHERE licensenumber IS NULL),
        fn_data AS (SELECT tenantid, applicationnumber,status,createdtime,'FirezNOC' AS servicename,financialyear
        FROM eg_fn_firenocdetail WHERE firestationid IS NULL),
        total_appl AS (
        SELECT tenantid, servicename, COUNT(*) AS cnt, financialyear FROM ws_data WHERE 1=1 GROUP BY tenantid, servicename, financialyear
        UNION ALL
        SELECT tenantid, servicename, COUNT(*) AS cnt, financialyear FROM sw_data WHERE 1=1 GROUP BY tenantid, servicename, financialyear
        UNION ALL
        SELECT tenantid, servicename, COUNT(*) AS cnt, financialyear FROM tl_data WHERE 1=1 GROUP BY tenantid, servicename, financialyear
        UNION ALL
        SELECT tenantid, servicename, COUNT(*) AS cnt, financialyear FROM fn_data WHERE 1=1 GROUP BY tenantid, servicename, financialyear),
        pending_appl AS (SELECT tenantid, applicationstatus, servicename, COUNT(*) AS cnt, financialyear
        FROM ws_data WHERE applicationstatus NOT IN ('CONNECTION_ACTIVATED', 'INITIATED','REJECTED','PENDING_FOR_CONNECTION_ACTIVATION','PENDING_FOR_PAYMENT')
        AND createdtime < (EXTRACT(EPOCH FROM now()) * 1000 - 11 * 24 * 60 * 60 * 1000)
        GROUP BY tenantid, applicationstatus, servicename, financialyear
        UNION ALL
        SELECT tenantid, applicationstatus, servicename, COUNT(*) AS cnt, financialyear
        FROM sw_data WHERE applicationstatus NOT IN ('CONNECTION_ACTIVATED', 'INITIATED','REJECTED','PENDING_FOR_CONNECTION_ACTIVATION','PENDING_FOR_PAYMENT')
        AND createdtime < (EXTRACT(EPOCH FROM now()) * 1000 - 11 * 24 * 60 * 60 * 1000)
        GROUP BY tenantid, applicationstatus, servicename, financialyear
        UNION ALL
        SELECT tenantid, status AS applicationstatus, servicename, COUNT(*) AS cnt, financialyear
        FROM tl_data WHERE status NOT IN ('INITIATED','REJECTED','PENDINGPAYMENT' , 'APPLIED','CANCELLED','APPROVED','CITIZENACTIONREQUIRED')
        AND createdtime < (EXTRACT(EPOCH FROM now()) * 1000 - 18 * 24 * 60 * 60 * 1000) 
        GROUP BY tenantid, status, servicename, financialyear
        UNION ALL
        SELECT tenantid, status AS applicationstatus, servicename, COUNT(*) AS cnt, financialyear
        FROM fn_data WHERE status NOT IN ('INITIATED','REJECTED','PENDINGPAYMENT','CANCELLED','APPROVED','CITIZENACTIONREQUIRED','CITIZENACTIONREQUIRED-DV')
        AND createdtime < (EXTRACT(EPOCH FROM now()) * 1000 - 20 * 24 * 60 * 60 * 1000)
        GROUP BY tenantid, status, servicename, financialyear)
        SELECT 'pb.punjab' as departmentID, 'Punjab Local Government' as departmentName, SUM(ta.cnt) AS TotalApplicationReceived, 
        COALESCE(SUM(pa.cnt), 0) AS PendingBeyondTimelineApplicationCount
        FROM total_appl ta LEFT JOIN pending_appl pa ON pa.tenantid = ta.tenantid
        AND pa.servicename = ta.servicename
        AND pa.financialyear = ta.financialyear
        WHERE ta.tenantid NOT IN ('pb.testing')
        
  - reportName: authority
    summary: Tenant Wise Pendency Report
    version: 1.0.0
    moduleName: authority
    sourceColumns:
      - name: authorityID
        label: authorityID
        type: string
        source: rainmaker-misc
        total: false
      - name: authorityName
        label: authorityName
        type: string
        source: rainmaker-misc
        total: false
      - name: departmentID
        label: departmentID
        type: string
        source: rainmaker-misc
        total: false
      - name: TotalApplicationReceived
        label: TotalApplicationReceived
        type: string
        source: rainmaker-misc
        total: false
      - name: PendingBeyondTimelineApplicationCount
        label: PendingBeyondTimelineApplicationCount
        type: string
        source: rainmaker-misc
        total: false
    searchParams:
      - name: tenantId
        label: tenantid
        type: singlevaluelist
        pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: rainmaker-misc
        wrapper: true
        isMandatory: false
        searchClause: AND authorityid =$tenantid
    query: |
       SELECT authorityid,authorityname,departmentid,totalapplicationreceived,pendingbeyondtimelineapplicationcount
       FROM public.authority_pendency_report WHERE 1=1
        
  - reportName: service
    summary: Service Wise Pendency Report
    version: 1.0.0
    moduleName: service
    sourceColumns:
      - name: serviceID
        label: serviceID
        type: string
        source: rainmaker-misc
        total: false
      - name: serviceName
        label: serviceName
        type: string
        source: rainmaker-misc
        total: false
      - name: authorityID
        label: authorityID
        type: string
        source: rainmaker-misc
        total: false
      - name: departmentID
        label: departmentID
        type: string
        source: rainmaker-misc
        total: false
      - name: TotalApplicationReceived
        label: TotalApplicationReceived
        type: string
        source: rainmaker-misc
        total: false
      - name: PendingBeyondTimelineApplicationCount
        label: PendingBeyondTimelineApplicationCount
        type: string
        source: rainmaker-misc
        total: false
    searchParams:
      - name: serviceID
        label: servicename
        type: singlevaluelist
        pattern: 'list://TL%:TL-Renewal,SW%:SW-Service,WS%:WS-Service,FN%:FireNoc,BS%:Bill Amendment'
        source: rainmaker-misc
        isMandatory: false
        searchClause: AND servicename =$serviceID
      - name: tenantId
        label: tenantid
        type: singlevaluelist
        pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: rainmaker-misc
        wrapper: true
        isMandatory: false
        searchClause: AND authorityid =$tenantid
    query: |
        SELECT serviceid,servicename,authorityid,departmentid,totalapplicationreceived,pendingbeyondtimelineapplicationcount
        FROM public.service_pendency_report WHERE 1=1

  - reportName: wspendencydetails
    summary: Pendency Details - Water Service
    version: 1.0.0
    moduleName: service
    sourceColumns:
      - name: tenantid
        label: tenantid
        type: string
        source: rainmaker-misc
        total: false
      - name: applicationno
        label: applicationno
        type: string
        source: rainmaker-misc
        total: false
      - name: applicationstatus
        label: applicationstatus
        type: string
        source: rainmaker-misc
        total: false
      - name: created_on
        label: created_on
        type: string
        source: rainmaker-misc
        total: false
      - name: assigned_to_employee
        label: assigned_to_employee
        type: string
        source: rainmaker-misc
        total: false
      - name: assigned_on
        label: assigned_on
        type: string
        source: rainmaker-misc
        total: false
    searchParams:
      - name: tenantId
        label: tenantid
        type: singlevaluelist
        pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: rainmaker-misc
        wrapper: true
        isMandatory: false
        searchClause: AND ta.tenantid =$tenantid
    query: |
        SELECT c.tenantid as tenantid, applicationno, applicationstatus,
        TO_CHAR(TO_TIMESTAMP(c.createdtime / 1000) AT TIME ZONE 'Asia/Kolkata', 'DD-MM-YYYY') as created_on,
        u.name as assigned_to_employee,
        TO_CHAR(TO_TIMESTAMP(assigned.createdtime / 1000) AT TIME ZONE 'Asia/Kolkata', 'DD-MM-YYYY') as assigned_on
        FROM eg_ws_connection c INNER JOIN ( SELECT id,businessid
        FROM eg_wf_processinstance_v2 pi
        WHERE (businessid, createdtime) IN (SELECT businessid, MAX(createdtime)
        FROM eg_wf_processinstance_v2
        GROUP BY businessid)) pi ON pi.businessid = c.applicationno
        left outer join eg_wf_assignee_v2 assigned on assigned.processinstanceid=pi.id
        left outer join eg_user u on u.uuid=assigned.assignee
        WHERE c.applicationstatus in ('PENDING_FOR_DOCUMENT_VERIFICATION','PENDING_FOR_FIELD_INSPECTION','PENDING_FOR_APPROVAL','PENDING_APPROVAL_FOR_CONNECTION')
        and c.createdtime < (EXTRACT(EPOCH FROM now()) * 1000 - 15 * 24 * 60 * 60 * 1000)
        AND c.tenantid = $tenantid
