serviceMaps:
 serviceName: sw-calculator-batch-logs
 mappings:
 - version: 1.0
   name: sw-calculator-batch-demand-log
   description: Persists tenant batch demand execution status logs for sewerage service
   fromTopic: save-sw-demand-log-v2
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_sw_batch_demand_log(id, tenantid, locality, taxperiodfrom, taxperiodto, insertiontime, totalconnectioncount, isdemandexecuted) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $
      jsonMaps:
       - jsonPath: $.id
       - jsonPath: $.tenantId
       - jsonPath: $.locality
       - jsonPath: $.taxPeriodFrom
       - jsonPath: $.taxPeriodTo
       - jsonPath: $.insertionTime
       - jsonPath: $.totalConnectionCount
       - jsonPath: $.isDemandExecuted

 - version: 1.0
   name: sw-calculator-connection-log
   description: Persists connection-level batch demand calculation logs for sewerage service
   fromTopic: save-sw-connection-log-v2
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_sw_batch_connection_log(id, connectionno, taxperiodfrom, taxperiodto, insertiondate, taxamount, tenantid) VALUES (?, ?, ?, ?, ?, ?, ?);
      basePath: $
      jsonMaps:
       - jsonPath: $.id
       - jsonPath: $.connectionNo
       - jsonPath: $.taxPeriodFrom
       - jsonPath: $.taxPeriodTo
       - jsonPath: $.insertionDate
       - jsonPath: $.taxAmount
       - jsonPath: $.tenantId
