SearchDefinitions:
  moduleName: advandhoarding-services
  summary: Advertisement Services Inbox API
  version: 1.0.0
  definitions:
    - name: inboxadvsearch
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(booking.booking_no), 
                   booking.createdtime, 
                   pi.status as status_id,
                   booking.booking_id,
                   booking.tenant_id,
                   booking.booking_status,
                   booking.application_date,
                   booking.payment_date
            from eg_adv_booking_detail as booking
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = booking.booking_no AND pi.latest = TRUE
            INNER JOIN eg_adv_owner ownerinfo ON ownerinfo.booking_id = booking.booking_id
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where 
            order by booking.createdtime asc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: booking.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: booking.booking_id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: booking.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: booking.booking_status
            isMandatory: false
            operator: IN
            jsonPath: $.searchCriteria.bookingStatus
          - name: applicant.applicant_mobile_no
            isMandatory: false
            jsonPath: $.searchCriteria.mobileNumber
          - name: ownerinfo.uuid
            isMandatory: false
            jsonPath: $.searchCriteria.userid
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"bookingApplication": []}
        outJsonPath: $.bookingApplication
        responseInfoPath: $.ResponseInfo

    - name: inboxadvsearchcount
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select COUNT(DISTINCT(booking.booking_no)) as totalCount
            from eg_adv_booking_detail as booking
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = booking.booking_no AND pi.latest = TRUE
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: booking.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: booking.booking_id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: booking.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: booking.booking_status
            isMandatory: false
            operator: IN
            jsonPath: $.searchCriteria.bookingStatus
          - name: applicant.applicant_mobile_no
            isMandatory: false
            jsonPath: $.searchCriteria.mobileNumber
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"totalCount": []}
        outJsonPath: $.totalCount
        responseInfoPath: $.ResponseInfo

    - name: inboxadvsearchdesc
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(booking.booking_no), 
                   booking.createdtime, 
                   pi.status as status_id,
                   booking.booking_id,
                   booking.tenant_id,
                   booking.booking_status,
                   booking.application_date,
                   booking.payment_date
            from eg_adv_booking_detail as booking
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = booking.booking_no AND pi.latest = TRUE
            INNER JOIN eg_adv_owner ownerinfo ON ownerinfo.booking_id = booking.booking_id
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            order by booking.createdtime desc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: booking.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: booking.booking_id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: booking.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: booking.booking_status
            isMandatory: false
            operator: IN
            jsonPath: $.searchCriteria.bookingStatus
          - name: applicant.applicant_mobile_no
            isMandatory: false
            jsonPath: $.searchCriteria.mobileNumber
          - name: ownerinfo.uuid
            isMandatory: false
            jsonPath: $.searchCriteria.userid
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"bookingApplication": []}
        outJsonPath: $.bookingApplication
        responseInfoPath: $.ResponseInfo
