SearchDefinitions:
  moduleName: clu-services
  summary: CLU Services Inbox API
  version: 1.0.0
  definitions:
    - name: inboxclusearch
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(clu.applicationno), 
                   clu.createdtime, 
                   pi.status as status_id,
                   clu.tenantid,
                   clu.status,
                   clu.cluno,
                   clu.applicationType,
                   clu.clutype,
                   clu.accountid,
                   clu.applicationstatus,
                   owner.ownertype,
                   owner.isprimaryowner,
                   owner.relationship,
                   owner.ownershippercentage
            from eg_clu as clu
            LEFT JOIN eg_clu_owner owner ON owner.cluid = clu.id 
            INNER JOIN (
              SELECT cluid, uuid as user_id FROM eg_clu_owner
              UNION
              SELECT id as cluid, createdby as user_id FROM eg_clu
            ) clu_user ON clu_user.cluid = clu.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = clu.applicationno
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where 
            AND pi.latest = TRUE
            order by clu.createdtime asc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: clu.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: clu.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: clu.applicationno
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: clu.cluno
            isMandatory: false
            jsonPath: $.searchCriteria.cluNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: clu.applicationstatus
            isMandatory: false
            jsonPath: $.searchCriteria.applicationStatus
          - name: clu.applicationType
            isMandatory: false
            jsonPath: $.searchCriteria.applicationType
          - name: clu.clutype
            isMandatory: false
            jsonPath: $.searchCriteria.cluType
          - name: clu.accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: owner.ownertype
            isMandatory: false
            jsonPath: $.searchCriteria.ownerType
          - name: clu.createdby
            isMandatory: false
            jsonPath: $.searchCriteria.userid
            operator: IN
          - name: owner.uuid
            isMandatory: false
            jsonPath: $.searchCriteria.ownerUuid
            operator: IN
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"cluApplication": []}
        outJsonPath: $.cluApplication
        responseInfoPath: $.ResponseInfo

    - name: inboxclusearchcount
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select COUNT(DISTINCT(clu.applicationno)) as totalCount
            from eg_clu as clu
            LEFT JOIN eg_clu_details details ON details.cluid = clu.id
            LEFT JOIN eg_clu_owner owner ON owner.cluid = clu.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = clu.applicationno
            LEFT JOIN eg_wf_state_v2 ws ON ws.uuid = pi.status
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            AND pi.createdtime IN (
              select max(createdtime) 
              from eg_wf_processinstance_v2 wf 
              where wf.businessid = clu.applicationno 
              GROUP BY wf.businessid
            )
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: clu.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: clu.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: clu.applicationno
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: clu.cluno
            isMandatory: false
            jsonPath: $.searchCriteria.cluNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: clu.applicationstatus
            isMandatory: false
            jsonPath: $.searchCriteria.applicationStatus
          - name: clu.applicationType
            isMandatory: false
            jsonPath: $.searchCriteria.applicationType
          - name: clu.clutype
            isMandatory: false
            jsonPath: $.searchCriteria.cluType
          - name: clu.accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: owner.ownertype
            isMandatory: false
            jsonPath: $.searchCriteria.ownerType
          - name: clu.createdby
            isMandatory: false
            jsonPath: $.searchCriteria.userid
            operator: IN
          - name: owner.uuid
            isMandatory: false
            jsonPath: $.searchCriteria.ownerUuid
            operator: IN

      output:
        jsonFormat: {"ResponseInfo": {},"totalCount": []}
        outJsonPath: $.totalCount
        responseInfoPath: $.ResponseInfo

    - name: inboxclusearchdesc
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(clu.applicationno), 
                   clu.createdtime, 
                   pi.status as status_id,
                   clu.id,
                   clu.tenantid,
                   clu.status,
                   clu.cluno,
                   clu.applicationType,
                   clu.clutype,
                   clu.accountid,
                   clu.applicationstatus,
                   owner.ownertype,
                   owner.isprimaryowner,
                   owner.relationship,
                   owner.ownershippercentage
            from eg_clu as clu
            LEFT JOIN eg_clu_owner owner ON owner.cluid = clu.id 
            INNER JOIN (
              SELECT cluid, uuid as user_id FROM eg_clu_owner
              UNION
              SELECT id as cluid, createdby as user_id FROM eg_clu
            ) clu_user ON clu_user.cluid = clu.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = clu.applicationno
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            AND pi.latest = TRUE
            order by clu.createdtime desc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: clu.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: clu.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: clu.applicationno
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: clu.cluno
            isMandatory: false
            jsonPath: $.searchCriteria.cluNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: clu.applicationstatus
            isMandatory: false
            jsonPath: $.searchCriteria.applicationStatus
          - name: clu.applicationType
            isMandatory: false
            jsonPath: $.searchCriteria.applicationType
          - name: clu.clutype
            isMandatory: false
            jsonPath: $.searchCriteria.cluType
          - name: clu.accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: owner.ownertype
            isMandatory: false
            jsonPath: $.searchCriteria.ownerType
          - name: clu.createdby
            isMandatory: false
            jsonPath: $.searchCriteria.userid
            operator: IN
          - name: owner.uuid
            isMandatory: false
            jsonPath: $.searchCriteria.ownerUuid
            operator: IN
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"cluApplication": []}
        outJsonPath: $.cluApplication
        responseInfoPath: $.ResponseInfo

    - name: inboxclucitizentenantwiseapplnsearch
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select clu.tenantid, clu.applicationno, pi.status as status_id from eg_clu as clu
            LEFT JOIN eg_clu_owner owner ON owner.cluid = clu.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = clu.applicationno
            $where 
            AND pi.latest = TRUE
            GROUP BY clu.tenantid, clu.applicationno, pi.status
          ) result
      searchParams:
        condition: AND
        params:
          - name: clu.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: clu.createdby
            isMandatory: false
            jsonPath: $.searchCriteria.userid
            operator: IN
          - name: owner.uuid
            isMandatory: false
            jsonPath: $.searchCriteria.ownerUuid
            operator: IN
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
      output:
        jsonFormat: {"ResponseInfo": {},"cluApplication": []}
        outJsonPath: $.cluApplication
        responseInfoPath: $.ResponseInfo