SearchDefinitions:
  moduleName: advandhoarding-services
  summary: Advertisement Services Inbox API
  version: 1.0.0
  definitions:
    - name: inboxadvsearch
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(booking.booking_no), 
                   pi.createdtime, 
                   pi.status as status_id, 
                   ws.state as status_name, 
                   ws.applicationStatus,
                   booking.booking_id,
                   booking.tenant_id,
                   booking.booking_status,
                   booking.application_date,
                   booking.payment_date,
                   applicant.applicant_name,
                   applicant.applicant_mobile_no,
                   applicant.applicant_email_id
            from eg_adv_booking_detail as booking
            INNER JOIN eg_adv_applicant_detail applicant ON applicant.booking_id = booking.booking_id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = booking.booking_no
            LEFT JOIN eg_wf_state_v2 ws ON ws.uuid = pi.status
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where 
            AND pi.createdtime IN (
              select max(createdtime) 
              from eg_wf_processinstance_v2 wf 
              where wf.businessid = booking.booking_no 
              GROUP BY wf.businessid
            )
            order by pi.createdtime asc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: booking.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: booking.booking_id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: booking.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: booking.booking_status
            isMandatory: false
            jsonPath: $.searchCriteria.bookingStatus
          - name: applicant.applicant_mobile_no
            isMandatory: false
            jsonPath: $.searchCriteria.mobileNumber
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"bookingApplication": []}
        outJsonPath: $.bookingApplication
        responseInfoPath: $.ResponseInfo

    - name: inboxadvsearchcount
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select COUNT(DISTINCT(booking.booking_no)) as totalCount
            from eg_adv_booking_detail as booking
            INNER JOIN eg_adv_applicant_detail applicant ON applicant.booking_id = booking.booking_id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = booking.booking_no
            LEFT JOIN eg_wf_state_v2 ws ON ws.uuid = pi.status
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            AND pi.createdtime IN (
              select max(createdtime) 
              from eg_wf_processinstance_v2 wf 
              where wf.businessid = booking.booking_no 
              GROUP BY wf.businessid
            )
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: booking.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: booking.booking_id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: booking.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: booking.booking_status
            isMandatory: false
            jsonPath: $.searchCriteria.bookingStatus
          - name: applicant.applicant_mobile_no
            isMandatory: false
            jsonPath: $.searchCriteria.mobileNumber
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"totalCount": []}
        outJsonPath: $.totalCount
        responseInfoPath: $.ResponseInfo

    - name: inboxadvsearchdesc
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(booking.booking_no), 
                   pi.createdtime, 
                   pi.status as status_id,
                   ws.state as status_name,
                   ws.applicationStatus,
                   booking.booking_id,
                   booking.tenant_id,
                   booking.booking_status,
                   booking.application_date,
                   booking.payment_date,
                   applicant.applicant_name,
                   applicant.applicant_mobile_no,
                   applicant.applicant_email_id
            from eg_adv_booking_detail as booking
            INNER JOIN eg_adv_applicant_detail applicant ON applicant.booking_id = booking.booking_id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = booking.booking_no
            LEFT JOIN eg_wf_state_v2 ws ON ws.uuid = pi.status
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            AND pi.createdtime IN (
              select max(createdtime) 
              from eg_wf_processinstance_v2 wf 
              where wf.businessid = booking.booking_no 
              GROUP BY wf.businessid
            )
            order by pi.createdtime desc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: booking.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: booking.booking_id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: booking.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: booking.booking_status
            isMandatory: false
            jsonPath: $.searchCriteria.bookingStatus
          - name: applicant.applicant_mobile_no
            isMandatory: false
            jsonPath: $.searchCriteria.mobileNumber
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"bookingApplication": []}
        outJsonPath: $.bookingApplication
        responseInfoPath: $.ResponseInfo