SearchDefinitions:
  moduleName: layout-services
  summary: Layout Services Inbox API
  version: 1.0.0
  definitions:
    - name: inboxlayoutsearch
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(layout.applicationno), 
                   layout.createdtime, 
                   pi.status as status_id, 
                   layout.id,
                   layout.tenantid,
                   layout.status,
                   layout.layoutno,
                   layout.applicationType,
                   layout.layouttype,
                   layout.accountid,
                   layout.applicationstatus,
                   owner.ownertype,
                   owner.isprimaryowner,
                   owner.relationship,
                   owner.ownershippercentage
            from eg_layout as layout
            LEFT JOIN eg_layout_owner owner ON owner.layoutid = layout.id AND owner.isprimaryowner = true
            INNER JOIN (
              SELECT layoutid, uuid as user_id FROM eg_layout_owner
              UNION
              SELECT id as layoutid, createdby as user_id FROM eg_layout
            ) layout_user ON layout_user.layoutid = layout.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = layout.applicationno
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where 
            AND pi.latest = TRUE
            order by layout.createdtime asc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: layout.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: layout.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: layout.applicationno
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: layout.layoutno
            isMandatory: false
            jsonPath: $.searchCriteria.layoutNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: layout.applicationstatus
            isMandatory: false
            jsonPath: $.searchCriteria.applicationStatus
          - name: layout.applicationType
            isMandatory: false
            jsonPath: $.searchCriteria.applicationType
          - name: layout.layouttype
            isMandatory: false
            jsonPath: $.searchCriteria.layoutType
          - name: layout.accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: owner.ownertype
            isMandatory: false
            jsonPath: $.searchCriteria.ownerType
          - name: layout_user.user_id
            isMandatory: false
            jsonPath: $.searchCriteria.userid
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"layoutApplication": []}
        outJsonPath: $.layoutApplication
        responseInfoPath: $.ResponseInfo

    - name: inboxlayoutsearchcount
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select COUNT(DISTINCT(layout.applicationno)) as totalCount
            from eg_layout as layout
            LEFT JOIN eg_layout_details details ON details.layoutid = layout.id
            LEFT JOIN eg_layout_owner owner ON owner.layoutid = layout.id AND owner.isprimaryowner = true
            INNER JOIN (
              SELECT layoutid, uuid as user_id FROM eg_layout_owner
              UNION
              SELECT id as layoutid, createdby as user_id FROM eg_layout
            ) layout_user ON layout_user.layoutid = layout.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = layout.applicationno
            LEFT JOIN eg_wf_state_v2 ws ON ws.uuid = pi.status
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            AND pi.latest = TRUE
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: layout.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: layout.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: layout.applicationno
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: layout.layoutno
            isMandatory: false
            jsonPath: $.searchCriteria.layoutNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: layout.applicationstatus
            isMandatory: false
            jsonPath: $.searchCriteria.applicationStatus
          - name: layout.applicationType
            isMandatory: false
            jsonPath: $.searchCriteria.applicationType
          - name: layout.layouttype
            isMandatory: false
            jsonPath: $.searchCriteria.layoutType
          - name: layout.accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: owner.ownertype
            isMandatory: false
            jsonPath: $.searchCriteria.ownerType
          - name: layout_user.user_id
            isMandatory: false
            jsonPath: $.searchCriteria.userid

      output:
        jsonFormat: {"ResponseInfo": {},"totalCount": []}
        outJsonPath: $.totalCount
        responseInfoPath: $.ResponseInfo

    - name: inboxlayoutsearchdesc
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select DISTINCT(layout.applicationno), 
                   layout.createdtime, 
                   pi.status as status_id,
                   layout.id,
                   layout.tenantid,
                   layout.status,
                   layout.layoutno,
                   layout.applicationType,
                   layout.layouttype,
                   layout.accountid,
                   layout.applicationstatus,
                   owner.ownertype,
                   owner.isprimaryowner,
                   owner.relationship,
                   owner.ownershippercentage
            from eg_layout as layout
            LEFT JOIN eg_layout_owner owner ON owner.layoutid = layout.id AND owner.isprimaryowner = true
            INNER JOIN (
              SELECT layoutid, uuid as user_id FROM eg_layout_owner
              UNION
              SELECT id as layoutid, createdby as user_id FROM eg_layout
            ) layout_user ON layout_user.layoutid = layout.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = layout.applicationno
            LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
            $where
            AND pi.latest = TRUE
            order by layout.createdtime desc
            $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: layout.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: layout.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
          - name: layout.applicationno
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNumber
          - name: layout.layoutno
            isMandatory: false
            jsonPath: $.searchCriteria.layoutNumber
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: layout.applicationstatus
            isMandatory: false
            jsonPath: $.searchCriteria.applicationStatus
          - name: layout.applicationType
            isMandatory: false
            jsonPath: $.searchCriteria.applicationType
          - name: layout.layouttype
            isMandatory: false
            jsonPath: $.searchCriteria.layoutType
          - name: layout.accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: owner.ownertype
            isMandatory: false
            jsonPath: $.searchCriteria.ownerType
          - name: layout_user.user_id
            isMandatory: false
            jsonPath: $.searchCriteria.userid
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {},"layoutApplication": []}
        outJsonPath: $.layoutApplication
        responseInfoPath: $.ResponseInfo

    - name: inboxlayoutcitizentenantwiseapplnsearch
      query:
        baseQuery: |
          Select row_to_json(result) from (
            select layout.tenantId, layout.applicationno, pi.status as status_id
            from eg_layout as layout
            LEFT JOIN eg_layout_owner owner ON owner.layoutid = layout.id AND owner.isprimaryowner = true
            INNER JOIN (
              SELECT layoutid, uuid as user_id FROM eg_layout_owner
              UNION
              SELECT id as layoutid, createdby as user_id FROM eg_layout
            ) layout_user ON layout_user.layoutid = layout.id
            INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = layout.applicationno
            $where
            AND pi.latest = TRUE
            GROUP BY layout.tenantId, layout.applicationno, pi.status
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: layout.tenantid
            isMandatory: true
            operator: ILIKE
            jsonPath: $.searchCriteria.tenantId
          - name: layout_user.user_id
            isMandatory: false
            jsonPath: $.searchCriteria.userid
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
            operator: IN
      output:
        jsonFormat: {"ResponseInfo": {},"layoutApplication": []}
        outJsonPath: $.layoutApplication
        responseInfoPath: $.ResponseInfo