SearchDefinitions:
  moduleName: swach-reform
  summary: Swach resolver for Rainmaker
  version: 1.0.0
  definitions:
    - name: serviceSearchWithDetails
      query:
        baseQuery: |
          SELECT array_to_json(array_agg(row_to_json(serviceRequests))) 
          FROM (
            SELECT (
              SELECT (
                SELECT row_to_json(services) 
                FROM (
                  SELECT *,
                    (SELECT row_to_json(auditDetails) 
                     FROM (
                       SELECT createdtime, lastmodifiedtime, createdby, lastmodifiedby 
                       FROM eg_swach_service_v2 
                       WHERE svc.serviceRequestId = eg_swach_service_v2.serviceRequestId
                     ) auditDetails
                    ) AS auditDetails,
                    (SELECT row_to_json(addressDetail) 
                     FROM (
                       SELECT * 
                       FROM eg_swach_address_v2 
                       WHERE eg_swach_address_v2.parentid = eg_swach_service_v2.id
                     ) addressDetail
                    ) AS addressDetail
                  FROM eg_swach_service_v2 svc 
                  WHERE svc.serviceRequestId = eg_swach_service_v2.serviceRequestId 
                  ORDER BY createdtime DESC
                ) services
              ) AS services
            ) FROM eg_swach_service_v2 $where 
            ORDER BY createdtime DESC $pagination
          ) serviceRequests
      searchParams:
        condition: AND
        params:
          - name: tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
            operator: LIKE
          - name: servicerequestid
            isMandatory: false
            jsonPath: $.searchCriteria.serviceRequestId
            operator: LIKE
          - name: servicerequestid
            isMandatory: false
            jsonPath: $.searchCriteria.complaintId
            operator: LIKE
          - name: accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: createdtime
            isMandatory: false
            operator: GE
            jsonPath: $.searchCriteria.startDate
          - name: createdtime
            isMandatory: false
            operator: LE
            jsonPath: $.searchCriteria.endDate
          - name: lastmodifiedtime
            isMandatory: false
            jsonPath: $.searchCriteria.lastUpdatedSince
          - name: serviceCode
            isMandatory: false
            jsonPath: $.searchCriteria.serviceCodes
          - name: phone
            isMandatory: false
            jsonPath: $.searchCriteria.phone
          - name: createdby
            isMandatory: false
            jsonPath: $.searchCriteria.createdBy
          - name: active
            isMandatory: false
            jsonPath: $.searchCriteria.active
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset
      output:
        jsonFormat: {"ResponseInfo": {}}
        outJsonPath: $.services
        responseInfoPath: $.ResponseInfo
    - name: count
      query:
        baseQuery: "SELECT row_to_json(services) FROM ( SELECT count(*) FROM public.eg_swach_service_v2 $where) AS services"
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
            operator: LIKE
          - name: servicerequestid
            isMandatory: false
            jsonPath: $.searchCriteria.serviceRequestId
            operator: LIKE
          - name: accountid
            isMandatory: false
            jsonPath: $.searchCriteria.accountId
          - name: status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: createdtime
            isMandatory: false
            operator: GE
            jsonPath: $.searchCriteria.startDate
          - name: createdtime
            isMandatory: false
            operator: LE
            jsonPath: $.searchCriteria.endDate
          - name: lastmodifiedtime
            isMandatory: false
            jsonPath: $.searchCriteria.lastUpdatedSince
          - name: serviceCode
            isMandatory: false
            jsonPath: $.searchCriteria.serviceCodes
          - name: phone
            isMandatory: false
            jsonPath: $.searchCriteria.phone
          - name: active
            isMandatory: false
            jsonPath: $.searchCriteria.active
      output:
        jsonFormat: {"ResponseInfo": {}}
        outJsonPath: $.count
        responseInfoPath: $.ResponseInfo
