ServiceMaps:
  serviceName: advertisement-booking-services
  version: 1.0.0
  mappings:

    - topic: save-advertisement-booking
      configKey: INDEX
      indexes:
        - name: ads-booking-application-index
          type: general
          id: $.bookingId
          isBulk: false
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.bookingApplication
          customJsonMapping:
            indexMapping: {"Data":{"bookingId":"bookingId","tenantId":"tenantId","bookingNo":"bookingNo",
                                   "applicationDate":"applicationDate","paymentDate":"paymentDate","draftId":"draftId",
                                   "receiptNo":"receiptNo","permissionLetterFilestoreId":"permissionLetterFilestoreId","paymentReceiptFilestoreId":"paymentReceiptFilestoreId",
                                   "bookingStatus":"bookingStatus","businessService":"businessService",
                                   "applicantDetailId":"applicantDetailId","applicantName":"applicantName","applicantMobileNo":"applicantMobileNo",
                                   "applicantAlternateMobileNo":"applicantAlternateMobileNo","applicantEmailId":"applicantEmailId",
                                   "createdBy":"createdBy","lastModifiedBy":"lastModifiedBy",
                                   "createdTime":"createdTime","lastModifiedTime":"lastModifiedTime",
                                   "addressId":"addressId","doorNo":"doorNo","houseNo":"houseNo","streetName":"streetName",
                                   "addressLine1":"addressLine1","addressLine2":"addressLine2","landmark":"landmark",
                                   "city":"city","cityCode":"cityCode","locality":"locality","localityCode":"localityCode","pincode":"pincode",
                                   "cartDetails":"cartDetails","documents":"documents","workflow":"workflow"}}
            fieldMapping:
              - inJsonPath: $.bookingId
                outJsonPath: $.Data.bookingId
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.bookingNo
                outJsonPath: $.Data.bookingNo
              - inJsonPath: $.applicationDate
                outJsonPath: $.Data.applicationDate
              - inJsonPath: $.paymentDate
                outJsonPath: $.Data.paymentDate
              - inJsonPath: $.draftId
                outJsonPath: $.Data.draftId
              - inJsonPath: $.receiptNo
                outJsonPath: $.Data.receiptNo
              - inJsonPath: $.permissionLetterFilestoreId
                outJsonPath: $.Data.permissionLetterFilestoreId
              - inJsonPath: $.paymentReceiptFilestoreId
                outJsonPath: $.Data.paymentReceiptFilestoreId
              - inJsonPath: $.bookingStatus
                outJsonPath: $.Data.bookingStatus
              - inJsonPath: $.businessService
                outJsonPath: $.Data.businessService
              - inJsonPath: $.auditDetails.createdBy
                outJsonPath: $.Data.createdBy
              - inJsonPath: $.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastModifiedBy
              - inJsonPath: $.auditDetails.createdTime
                outJsonPath: $.Data.createdTime
              - inJsonPath: $.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastModifiedTime
              - inJsonPath: $.applicantDetail.applicantDetailId
                outJsonPath: $.Data.applicantDetailId
              - inJsonPath: $.applicantDetail.applicantName
                outJsonPath: $.Data.applicantName
              - inJsonPath: $.applicantDetail.applicantMobileNo
                outJsonPath: $.Data.applicantMobileNo
              - inJsonPath: $.applicantDetail.applicantAlternateMobileNo
                outJsonPath: $.Data.applicantAlternateMobileNo
              - inJsonPath: $.applicantDetail.applicantEmailId
                outJsonPath: $.Data.applicantEmailId
              - inJsonPath: $.address.addressId
                outJsonPath: $.Data.addressId
              - inJsonPath: $.address.doorNo
                outJsonPath: $.Data.doorNo
              - inJsonPath: $.address.houseNo
                outJsonPath: $.Data.houseNo
              - inJsonPath: $.address.streetName
                outJsonPath: $.Data.streetName
              - inJsonPath: $.address.addressLine1
                outJsonPath: $.Data.addressLine1
              - inJsonPath: $.address.addressLine2
                outJsonPath: $.Data.addressLine2
              - inJsonPath: $.address.landmark
                outJsonPath: $.Data.landmark
              - inJsonPath: $.address.city
                outJsonPath: $.Data.city
              - inJsonPath: $.address.cityCode
                outJsonPath: $.Data.cityCode
              - inJsonPath: $.address.locality
                outJsonPath: $.Data.locality
              - inJsonPath: $.address.localityCode
                outJsonPath: $.Data.localityCode
              - inJsonPath: $.address.pincode
                outJsonPath: $.Data.pincode
              - inJsonPath: $.cartDetails
                outJsonPath: $.Data.cartDetails
              - inJsonPath: $.documents
                outJsonPath: $.Data.documents
              - inJsonPath: $.workflow
                outJsonPath: $.Data.workflow

    - topic: update-advertisement-booking
      configKey: INDEX
      indexes:
        - name: ads-booking-application-update-index
          type: general
          id: $.bookingId, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.bookingApplication.*
          customJsonMapping:
            indexMapping: {"Data":{"bookingId":"bookingId","tenantId":"tenantId","bookingNo":"bookingNo",
                                   "bookingStatus":"bookingStatus","paymentDate":"paymentDate","receiptNo":"receiptNo",
                                   "applicantName":"applicantName","applicantMobileNo":"applicantMobileNo",
                                   "lastModifiedBy":"lastModifiedBy","lastModifiedTime":"lastModifiedTime",
                                   "addressLine1":"addressLine1","city":"city","pincode":"pincode",
                                   "cartDetails":"cartDetails"}}
            fieldMapping:
              - inJsonPath: $.bookingId
                outJsonPath: $.Data.bookingId
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.bookingNo
                outJsonPath: $.Data.bookingNo
              - inJsonPath: $.applicationDate
                outJsonPath: $.Data.applicationDate
              - inJsonPath: $.paymentDate
                outJsonPath: $.Data.paymentDate
              - inJsonPath: $.draftId
                outJsonPath: $.Data.draftId
              - inJsonPath: $.receiptNo
                outJsonPath: $.Data.receiptNo
              - inJsonPath: $.permissionLetterFilestoreId
                outJsonPath: $.Data.permissionLetterFilestoreId
              - inJsonPath: $.paymentReceiptFilestoreId
                outJsonPath: $.Data.paymentReceiptFilestoreId
              - inJsonPath: $.bookingStatus
                outJsonPath: $.Data.bookingStatus
              - inJsonPath: $.businessService
                outJsonPath: $.Data.businessService
              - inJsonPath: $.auditDetails.createdBy
                outJsonPath: $.Data.createdBy
              - inJsonPath: $.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastModifiedBy
              - inJsonPath: $.auditDetails.createdTime
                outJsonPath: $.Data.createdTime
              - inJsonPath: $.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastModifiedTime
              - inJsonPath: $.applicantDetail.applicantDetailId
                outJsonPath: $.Data.applicantDetailId
              - inJsonPath: $.applicantDetail.applicantName
                outJsonPath: $.Data.applicantName
              - inJsonPath: $.applicantDetail.applicantMobileNo
                outJsonPath: $.Data.applicantMobileNo
              - inJsonPath: $.applicantDetail.applicantAlternateMobileNo
                outJsonPath: $.Data.applicantAlternateMobileNo
              - inJsonPath: $.applicantDetail.applicantEmailId
                outJsonPath: $.Data.applicantEmailId
              - inJsonPath: $.address.addressId
                outJsonPath: $.Data.addressId
              - inJsonPath: $.address.doorNo
                outJsonPath: $.Data.doorNo
              - inJsonPath: $.address.houseNo
                outJsonPath: $.Data.houseNo
              - inJsonPath: $.address.streetName
                outJsonPath: $.Data.streetName
              - inJsonPath: $.address.addressLine1
                outJsonPath: $.Data.addressLine1
              - inJsonPath: $.address.addressLine2
                outJsonPath: $.Data.addressLine2
              - inJsonPath: $.address.landmark
                outJsonPath: $.Data.landmark
              - inJsonPath: $.address.city
                outJsonPath: $.Data.city
              - inJsonPath: $.address.cityCode
                outJsonPath: $.Data.cityCode
              - inJsonPath: $.address.locality
                outJsonPath: $.Data.locality
              - inJsonPath: $.address.localityCode
                outJsonPath: $.Data.localityCode
              - inJsonPath: $.address.pincode
                outJsonPath: $.Data.pincode
              - inJsonPath: $.cartDetails
                outJsonPath: $.Data.cartDetails
              - inJsonPath: $.documents
                outJsonPath: $.Data.documents
              - inJsonPath: $.workflow
                outJsonPath: $.Data.workflow