ServiceMaps:
  serviceName: adv-services
  version: 1.0.0
  mappings:

    - topic: save-advertisement-booking
      configKey: INDEX
      indexes:
        - name: advertisement-booking-index
          type: general
          id: $.bookingId
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.bookingApplication
          customJsonMapping:
            indexMapping: {"Data":{"bookingId":"bookingId","bookingNo":"bookingNo","paymentDate":"paymentDate",
                                   "applicationDate":"applicationDate","tenantId":"tenantId","bookingStatus":"bookingStatus",
                                   "receiptNo":"receiptNo","createdby":"createdby","lastmodifiedby":"lastmodifiedby",
                                   "createdtime":"createdtime","lastmodifiedtime":"lastmodifiedtime","cartDetails":[],"documents":[],
                                   "applicantDetail":{},"address":{},"permissionLetterFilestoreId":"permissionLetterFilestoreId",
                                   "paymentReceiptFilestoreId":"paymentReceiptFilestoreId"}}
            fieldMapping:
              - inJsonPath: $.bookingApplication.bookingId
                outJsonPath: $.Data.bookingId
              - inJsonPath: $.bookingApplication.bookingNo
                outJsonPath: $.Data.bookingNo
              - inJsonPath: $.bookingApplication.paymentDate
                outJsonPath: $.Data.paymentDate
              - inJsonPath: $.bookingApplication.applicationDate
                outJsonPath: $.Data.applicationDate
              - inJsonPath: $.bookingApplication.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.bookingApplication.bookingStatus
                outJsonPath: $.Data.bookingStatus
              - inJsonPath: $.bookingApplication.receiptNo
                outJsonPath: $.Data.receiptNo
              - inJsonPath: $.bookingApplication.auditDetails.createdBy
                outJsonPath: $.Data.createdby
              - inJsonPath: $.bookingApplication.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.bookingApplication.auditDetails.createdTime
                outJsonPath: $.Data.createdtime
              - inJsonPath: $.bookingApplication.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime
              - inJsonPath: $.bookingApplication.cartDetails
                outJsonPath: $.Data.cartDetails
              - inJsonPath: $.bookingApplication.documents
                outJsonPath: $.Data.documents
              - inJsonPath: $.bookingApplication.applicantDetail
                outJsonPath: $.Data.applicantDetail
              - inJsonPath: $.bookingApplication.address
                outJsonPath: $.Data.address
              - inJsonPath: $.bookingApplication.permissionLetterFilestoreId
                outJsonPath: $.Data.permissionLetterFilestoreId
              - inJsonPath: $.bookingApplication.paymentReceiptFilestoreId
                outJsonPath: $.Data.paymentReceiptFilestoreId

    - topic: update-advertisement-booking
      configKey: INDEX
      indexes:
        - name: advertisement-booking-update-index
          type: general
          id: $.bookingId, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.bookingApplication
          customJsonMapping:
            indexMapping: {"Data":{"bookingId":"bookingId","bookingNo":"bookingNo","paymentDate":"paymentDate",
                                   "applicationDate":"applicationDate","tenantId":"tenantId","bookingStatus":"bookingStatus",
                                   "receiptNo":"receiptNo","lastmodifiedby":"lastmodifiedby","lastmodifiedtime":"lastmodifiedtime",
                                   "cartDetails":[],"documents":[],"applicantDetail":{},"address":{},"permissionLetterFilestoreId":"permissionLetterFilestoreId",
                                   "paymentReceiptFilestoreId":"paymentReceiptFilestoreId"}}
            fieldMapping:
              - inJsonPath: $.bookingApplication.bookingId
                outJsonPath: $.Data.bookingId
              - inJsonPath: $.bookingApplication.bookingNo
                outJsonPath: $.Data.bookingNo
              - inJsonPath: $.bookingApplication.paymentDate
                outJsonPath: $.Data.paymentDate
              - inJsonPath: $.bookingApplication.applicationDate
                outJsonPath: $.Data.applicationDate
              - inJsonPath: $.bookingApplication.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.bookingApplication.bookingStatus
                outJsonPath: $.Data.bookingStatus
              - inJsonPath: $.bookingApplication.receiptNo
                outJsonPath: $.Data.receiptNo
              - inJsonPath: $.bookingApplication.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.bookingApplication.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime
              - inJsonPath: $.bookingApplication.cartDetails
                outJsonPath: $.Data.cartDetails
              - inJsonPath: $.bookingApplication.documents
                outJsonPath: $.Data.documents
              - inJsonPath: $.bookingApplication.applicantDetail
                outJsonPath: $.Data.applicantDetail
              - inJsonPath: $.bookingApplication.address
                outJsonPath: $.Data.address
              - inJsonPath: $.bookingApplication.permissionLetterFilestoreId
                outJsonPath: $.Data.permissionLetterFilestoreId
              - inJsonPath: $.bookingApplication.paymentReceiptFilestoreId
                outJsonPath: $.Data.paymentReceiptFilestoreId

    - topic: create-draft-advertisement
      configKey: INDEX
      indexes:
        - name: advertisement-draft-index
          type: general
          id: $.draftId
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.advertisementDraftDetail
          customJsonMapping:
            indexMapping: {"Data":{"draftId":"draftId","tenantId":"tenantId","userUuid":"userUuid",
                                   "draftApplicationData":"draftApplicationData","createdby":"createdby","lastmodifiedby":"lastmodifiedby",
                                   "createdtime":"createdtime","lastmodifiedtime":"lastmodifiedtime"}}
            fieldMapping:
              - inJsonPath: $.advertisementDraftDetail.draftId
                outJsonPath: $.Data.draftId
              - inJsonPath: $.advertisementDraftDetail.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.advertisementDraftDetail.userUuid
                outJsonPath: $.Data.userUuid
              - inJsonPath: $.advertisementDraftDetail.draftApplicationData
                outJsonPath: $.Data.draftApplicationData
              - inJsonPath: $.advertisementDraftDetail.auditDetails.createdBy
                outJsonPath: $.Data.createdby
              - inJsonPath: $.advertisementDraftDetail.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.advertisementDraftDetail.auditDetails.createdTime
                outJsonPath: $.Data.createdtime
              - inJsonPath: $.advertisementDraftDetail.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime

    - topic: update-draft-advertisement
      configKey: INDEX
      indexes:
        - name: advertisement-draft-update-index
          type: general
          id: $.draftId, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.advertisementDraftDetail
          customJsonMapping:
            indexMapping: {"Data":{"draftId":"draftId","tenantId":"tenantId","userUuid":"userUuid",
                                   "draftApplicationData":"draftApplicationData","lastmodifiedby":"lastmodifiedby",
                                   "lastmodifiedtime":"lastmodifiedtime"}}
            fieldMapping:
              - inJsonPath: $.advertisementDraftDetail.draftId
                outJsonPath: $.Data.draftId
              - inJsonPath: $.advertisementDraftDetail.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.advertisementDraftDetail.userUuid
                outJsonPath: $.Data.userUuid
              - inJsonPath: $.advertisementDraftDetail.draftApplicationData
                outJsonPath: $.Data.draftApplicationData
              - inJsonPath: $.advertisementDraftDetail.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.advertisementDraftDetail.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime

    - topic: delete-draft-advertisement
      configKey: INDEX
      indexes:
        - name: advertisement-draft-delete-index
          type: general
          id: $.draftId, $.tenantId
          isBulk: false
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.advertisementDraftDetail
          customJsonMapping:
            indexMapping: {"Data":{"draftId":"draftId","deleted":"deleted","lastmodifiedby":"lastmodifiedby",
                                   "lastmodifiedtime":"lastmodifiedtime"}}
            fieldMapping:
              - inJsonPath: $.advertisementDraftDetail.draftId
                outJsonPath: $.Data.draftId
              - jsonPath: "true"
                outJsonPath: $.Data.deleted
              - inJsonPath: $.advertisementDraftDetail.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.advertisementDraftDetail.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime
