ServiceMaps:
  serviceName: egov-ndc-services
  version: 1.0.0
  mappings:
    - topic: save-ndc-application
      configKey: INDEX
      indexes:
        - name: ndc-application-index
          type: general
          id: $.Applications.*.uuid, $.Application.*.tenantId
          isBulk: true
          timeStampField: $.Applications.*.auditDetails.createdTime
          jsonPath: $
          customJsonMapping:
            indexMapping: {"Data":{"uuid":"uuid","tenantId":"tenantId","owners":[]
                                   "applicationStatus":"applicationStatus","active":"active",
                                   "createdby":"createdby","lastmodifiedby":"lastmodifiedby","createdtime":"createdtime",
                                   "lastmodifiedtime":"lastmodifiedtime","action":"action","details":[],"documents:[]","reason":"reason"}}
            fieldMapping:
              - inJsonPath: $.Applications.*.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.Applications.*.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.Applications.*.owners
                outJsonPath: $.Data.owners
              - inJsonPath: $.Applications.*.applicationStatus
                outJsonPath: $.Data.applicationStatus
              - inJsonPath: $.Applications.*.active
                outJsonPath: $.Data.active
              - inJsonPath: $.Applications.*.auditDetails.createdBy
                outJsonPath: $.Data.createdby
              - inJsonPath: $.Applications.*.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.Applications.*.auditDetails.createdTime
                outJsonPath: $.Data.createdtime
              - inJsonPath: $.Applications.*.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime
              - inJsonPath: $.Applications.*.action
                outJsonPath: $.Data.action
              - inJsonPath: $.Application.*.NdcDetails
                outJsonPath: $.Data.details
              - inJsonPath: $.Application.*.Documents
                outJsonPath: $.Data.documents
              - inJsonPath: $.Applications.*.reason
                outJsonPath: $.Data.reason

    - topic: update-ndc-application
      configKey: INDEX
      indexes:
        - name: ndc-application-update-index
          type: general
          id: $.Applications.*.uuid, $.Applications.*.tenantId
          isBulk: true
          timeStampField: $.Applications.*.auditDetails.lastModifiedTime
          jsonPath: $
          customJsonMapping:
            indexMapping: {"Data":{"uuid":"uuid","tenantId":"tenantId","owners":[],
                                   "applicationStatus":"applicationStatus","active":"active",
                                   "lastmodifiedby":"lastmodifiedby","lastmodifiedtime":"lastmodifiedtime",
                                   "action":"action","details":[],"documents:[]","reason":"reason"}}
            fieldMapping:
              - inJsonPath: $.Applications.*.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.Applications.*.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.Applications.*.owners
                outJsonPath: $.Data.owners
              - inJsonPath: $.Applications.*.applicationStatus
                outJsonPath: $.Data.applicationStatus
              - inJsonPath: $.Applications.*.active
                outJsonPath: $.Data.active
              - inJsonPath: $.Applications.*.auditDetails.createdBy
                outJsonPath: $.Data.createdby
              - inJsonPath: $.Applications.*.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.Applications.*.auditDetails.createdTime
                outJsonPath: $.Data.createdtime
              - inJsonPath: $.Applications.*.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastmodifiedtime
              - inJsonPath: $.Applications.*.action
                outJsonPath: $.Data.action
              - inJsonPath: $.Applications.*.NdcDetails
                outJsonPath: $.Data.details
              - inJsonPath: $.Applications.*.Documents
                outJsonPath: $.Data.documents
              - inJsonPath: $.Applications.*.reason
                outJsonPath: $.Data.reason

    - topic: delete-ndc-application
      configKey: INDEX
      indexes:
        - name: ndc-applicants-delete-index
          type: general
          id: $.uuid, $.tenantId
          isBulk: false
          timeStampField: $.lastmodifiedtime
          jsonPath: $
          customJsonMapping:
            indexMapping: {"Data":{"uuid":"uuid","active":"active","lastmodifiedby":
              "lastmodifiedby","lastmodifiedtime":"lastmodifiedtime"}}
            fieldMapping:
              - inJsonPath: $.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.active
                outJsonPath: $.Data.active
              - inJsonPath: $.lastmodifiedby
                outJsonPath: $.Data.lastmodifiedby
              - inJsonPath: $.lastmodifiedtime
                outJsonPath: $.Data.lastmodifiedtime