ServiceMaps:
  serviceName: Survey Service
  version: 1.0.0
  mappings:
    - topic: save-ss-category
      configKey: INDEX
      indexes:
        - name: survey-category-index
          type: general
          id: $.id, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.Categories.*
          customJsonMapping:
            indexMapping: {"Data":{"id": "id","label": "label","isActive": "isActive","tenantId": "","auditDetails": {}}}
            fieldMapping:
              - inJsonPath: $.id
                outJsonPath: $.Data.id
              - inJsonPath: $.label
                outJsonPath: $.Data.label
              - inJsonPath: $.isActive
                outJsonPath: $.Data.isActive
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails

    - topic: update-ss-category
      configKey: INDEX
      indexes:
        - name: survey-category-update-index
          type: general
          id: $.id, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.Categories.*
          customJsonMapping:
            indexMapping: {"Data":{"id": "id","label": "label","isActive": "isActive","tenantId": "tenantId","lastModifiedBy": "lastModifiedBy","lastModifiedTime": "lastModifiedTime","auditDetails": {}}}
            fieldMapping:
              - inJsonPath: $.id
                outJsonPath: $.Data.id
              - inJsonPath: $.label
                outJsonPath: $.Data.label
              - inJsonPath: $.isActive
                outJsonPath: $.Data.isActive
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastModifiedBy
              - inJsonPath: $.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastModifiedTime
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails

    - topic: save-ss-question
      configKey: INDEX
      indexes:
        - name: survey-question-index
          type: general
          id: $.uuid, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.Questions.*
          customJsonMapping:
            indexMapping: {"Data":{"uuid": "uuid","tenantId": "tenantId","questionStatement": "questionStatement","status": "status","type": "type","categoryId": "categoryId","auditDetails": {},"options": []}}
            fieldMapping:
              - inJsonPath: $.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.questionStatement
                outJsonPath: $.Data.questionStatement
              - inJsonPath: $.status
                outJsonPath: $.Data.status
              - inJsonPath: $.type
                outJsonPath: $.Data.type
              - inJsonPath: $.categoryId
                outJsonPath: $.Data.categoryId
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails
              - inJsonPath: $.options.*.uuid
                outJsonPath: $.Data.options
              - inJsonPath: $.options.*.questionUuid
                outJsonPath: $.Data.options
              - inJsonPath: $.options.*.optionText
                outJsonPath: $.Data.options
              - inJsonPath: $.options.*.weightage
                outJsonPath: $.Data.options
              - inJsonPath: $.options.*.auditDetails
                outJsonPath: $.Data.options

    - topic: update-ss-question
      configKey: INDEX
      indexes:
        - name: survey-question-update-index
          type: general
          id: $.uuid, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.Questions.*
          customJsonMapping:
            indexMapping: {"Data":{"uuid": "uuid","tenantId": "tenantId","status": "status","lastModifiedBy": "lastModifiedBy","lastModifiedTime": "lastModifiedTime","auditDetails": {}}}
            fieldMapping:
              - inJsonPath: $.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.status
                outJsonPath: $.Data.status
              - inJsonPath: $.auditDetails.lastModifiedBy
                outJsonPath: $.Data.lastModifiedBy
              - inJsonPath: $.auditDetails.lastModifiedTime
                outJsonPath: $.Data.lastModifiedTime
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails

    - topic: insert-scorecard-survey-entity
      configKey: INDEX
      indexes:
        - name: survey-entity-index
          type: general
          id: $.uuid, $.tenantId
          isBulk: false
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.SurveyEntity
          customJsonMapping:
            indexMapping: { "Data": { "uuid": "uuid", "tenantId": "tenantId", "surveyTitle": "surveyTitle", "surveyCategory": "surveyCategory", "surveyDescription": "surveyDescription", "startDate": "startDate", "endDate": "endDate", "postedBy": "postedBy", "active": "active", "answersCount": "answersCount", "hasResponded": "hasResponded", "auditDetails": {}, "sections": [] } }
            fieldMapping:
              - inJsonPath: $.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.surveyTitle
                outJsonPath: $.Data.surveyTitle
              - inJsonPath: $.surveyCategory
                outJsonPath: $.Data.surveyCategory
              - inJsonPath: $.surveyDescription
                outJsonPath: $.Data.surveyDescription
              - inJsonPath: $.startDate
                outJsonPath: $.Data.startDate
              - inJsonPath: $.endDate
                outJsonPath: $.Data.endDate
              - inJsonPath: $.postedBy
                outJsonPath: $.Data.postedBy
              - inJsonPath: $.active
                outJsonPath: $.Data.active
              - inJsonPath: $.answersCount
                outJsonPath: $.Data.answersCount
              - inJsonPath: $.hasResponded
                outJsonPath: $.Data.hasResponded
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails

              # Section Responses Mapping
              - inJsonPath: $.sections
                outJsonPath: $.Data.sections
#              - inJsonPath: $.sections.*.title
#                outJsonPath: $.Data.sections
#              - inJsonPath: $.sections.*.weightage
#                outJsonPath: $.Data.sections
#              - inJsonPath: $.sections.*.sectionOrder
#                outJsonPath: $.Data.sections
#
#              # Question Responses Mapping
#              - inJsonPath: $.sections.*.questions.*.questionUuid
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.qorder
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.question.questionStatement
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.question.uuid
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.question.status
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.question.type
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.question.categoryId
#                outJsonPath: $.Data.questions
#              - inJsonPath: $.sections.*.questions.*.question.auditDetails
#                outJsonPath: $.Data.questions
#
#              # Mapping Question Options
#              - inJsonPath: $.sections.*.questions.*.question.options.*.uuid
#                outJsonPath: $.Data.questionResponses.*.options
#              - inJsonPath: $.sections.*.questions.*.question.options.*.optionText
#                outJsonPath: $.Data.questionResponses.*.options
#              - inJsonPath: $.sections.*.questions.*.question.options.*.weightage
#                outJsonPath: $.Data.questionResponses.*.options
#              - inJsonPath: $.sections.*.questions.*.question.options.*.auditDetails
#                outJsonPath: $.Data.questionResponses.*.options

    - topic: update-scorecard-survey-active
      configKey: INDEX
      indexes:
        - name: survey-entity-update-index
          type: general
          id: $.uuid, $.tenantId
          isBulk: true
          timeStampField: $.lastModifiedTime
          jsonPath: $
          customJsonMapping:
            indexMapping: {"Data":{"uuid": "uuid","tenantId": "tenantId","active": "active","lastModifiedBy": "lastModifiedBy","lastModifiedTime": "lastModifiedTime","auditDetails": {}}}
            fieldMapping:
              - inJsonPath: $.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.tenantId
                outJsonPath: $.Data.tenantId
              - inJsonPath: $.active
                outJsonPath: $.Data.active
              - inJsonPath: $.lastModifiedBy
                outJsonPath: $.Data.lastModifiedBy
              - inJsonPath: $.lastModifiedTime
                outJsonPath: $.Data.lastModifiedTime
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails

    - topic: save-ss-answer
      configKey: INDEX
      indexes:
        - name: survey-answer-index
          type: general
          id: $.uuid, $.surveyResponseUuid
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.SurveyResponse.answers.*
          customJsonMapping:
            indexMapping: {"Data":{"uuid": "uuid","questionUuid": "questionUuid","surveyResponseUuid": "surveyResponseUuid","sectionUuid": "sectionUuid","comments": "comments","auditDetails": {},"answerDetails": []}}
            fieldMapping:
              - inJsonPath: $.uuid
                outJsonPath: $.Data.uuid
              - inJsonPath: $.questionUuid
                outJsonPath: $.Data.questionUuid
              - inJsonPath: $.surveyResponseUuid
                outJsonPath: $.Data.surveyResponseUuid
              - inJsonPath: $.sectionUuid
                outJsonPath: $.Data.sectionUuid
              - inJsonPath: $.comments
                outJsonPath: $.Data.comments
              - inJsonPath: $.auditDetails
                outJsonPath: $.Data.auditDetails
              - inJsonPath: $.answerDetails.*.uuid
                outJsonPath: $.Data.answerDetails
              - inJsonPath: $.answerDetails.*.answerUuid
                outJsonPath: $.Data.answerDetails
              - inJsonPath: $.answerDetails.*.answerType
                outJsonPath: $.Data.answerDetails
              - inJsonPath: $.answerDetails.*.answerContent
                outJsonPath: $.Data.answerDetails
              - inJsonPath: $.answerDetails.*.weightage
                outJsonPath: $.Data.answerDetails
              - inJsonPath: $.answerDetails.*.comments
                outJsonPath: $.Data.answerDetails
              - inJsonPath: $.answerDetails.*.auditDetails
                outJsonPath: $.Data.answerDetails