ServiceMaps:
  serviceName: pet-services
  version: 1.0.0
  mappings:

    - topic: save-ptr-application
      configKey: INDEX
      indexes:
        - name: ptr-application-index
          type: general
          id: $.id
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.PetRegistrationApplications.*
          customJsonMapping:
            indexMapping: {"Data":{"id":"id","tenantId":"tenantId","applicationNumber":"applicationNumber",
                                   "applicantName":"applicantName","fatherName":"fatherName","mobileNumber":"mobileNumber",
                                   "emailId":"emailId","applicationType":"applicationType","validityDate":"validityDate",
                                   "status":"status","expireFlag":"expireFlag","petToken":"petToken","previousApplicationNumber":"previousApplicationNumber",
                                   "propertyId":"propertyId","createdby":"createdby","lastmodifiedby":"lastmodifiedby",
                                   "createdtime":"createdtime","lastmodifiedtime":"lastmodifiedtime","address":{},"petDetails":{},"documents":[]}}
          fieldMapping:
            - inJsonPath: $.PetRegistrationApplications.*.id
              outJsonPath: $.Data.id
            - inJsonPath: $.PetRegistrationApplications.*.tenantId
              outJsonPath: $.Data.tenantId
            - inJsonPath: $.PetRegistrationApplications.*.applicationNumber
              outJsonPath: $.Data.applicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.applicantName
              outJsonPath: $.Data.applicantName
            - inJsonPath: $.PetRegistrationApplications.*.fatherName
              outJsonPath: $.Data.fatherName
            - inJsonPath: $.PetRegistrationApplications.*.mobileNumber
              outJsonPath: $.Data.mobileNumber
            - inJsonPath: $.PetRegistrationApplications.*.emailId
              outJsonPath: $.Data.emailId
            - inJsonPath: $.PetRegistrationApplications.*.applicationType
              outJsonPath: $.Data.applicationType
            - inJsonPath: $.PetRegistrationApplications.*.validityDate
              outJsonPath: $.Data.validityDate
            - inJsonPath: $.PetRegistrationApplications.*.status
              outJsonPath: $.Data.status
            - inJsonPath: $.PetRegistrationApplications.*.expireFlag
              outJsonPath: $.Data.expireFlag
            - inJsonPath: $.PetRegistrationApplications.*.petToken
              outJsonPath: $.Data.petToken
            - inJsonPath: $.PetRegistrationApplications.*.previousApplicationNumber
              outJsonPath: $.Data.previousApplicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.propertyId
              outJsonPath: $.Data.propertyId
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.createdBy
              outJsonPath: $.Data.createdby
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy
              outJsonPath: $.Data.lastmodifiedby
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.createdTime
              outJsonPath: $.Data.createdtime
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime
              outJsonPath: $.Data.lastmodifiedtime
            - inJsonPath: $.PetRegistrationApplications.*.address
              outJsonPath: $.Data.address
            - inJsonPath: $.PetRegistrationApplications.*.petDetails
              outJsonPath: $.Data.petDetails
            - inJsonPath: $.PetRegistrationApplications.*.documents
              outJsonPath: $.Data.documents

    - topic: update-ptr-application
      configKey: INDEX
      indexes:
        - name: ptr-application-update-index
          type: general
          id: $.id, $.tenantId
          isBulk: true
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.PetRegistrationApplications.*
          customJsonMapping:
            indexMapping: {"Data":{"id":"id","tenantId":"tenantId","applicationNumber":"applicationNumber",
                                   "applicantName":"applicantName","fatherName":"fatherName","mobileNumber":"mobileNumber",
                                   "emailId":"emailId","applicationType":"applicationType","validityDate":"validityDate",
                                   "status":"status","expireFlag":"expireFlag","petToken":"petToken","previousApplicationNumber":"previousApplicationNumber",
                                   "propertyId":"propertyId","lastmodifiedby":"lastmodifiedby","lastmodifiedtime":"lastmodifiedtime",
                                   "address":{},"petDetails":{},"documents":[]}}
          fieldMapping:
            - inJsonPath: $.PetRegistrationApplications.*.id
              outJsonPath: $.Data.id
            - inJsonPath: $.PetRegistrationApplications.*.tenantId
              outJsonPath: $.Data.tenantId
            - inJsonPath: $.PetRegistrationApplications.*.applicationNumber
              outJsonPath: $.Data.applicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.applicantName
              outJsonPath: $.Data.applicantName
            - inJsonPath: $.PetRegistrationApplications.*.fatherName
              outJsonPath: $.Data.fatherName
            - inJsonPath: $.PetRegistrationApplications.*.mobileNumber
              outJsonPath: $.Data.mobileNumber
            - inJsonPath: $.PetRegistrationApplications.*.emailId
              outJsonPath: $.Data.emailId
            - inJsonPath: $.PetRegistrationApplications.*.applicationType
              outJsonPath: $.Data.applicationType
            - inJsonPath: $.PetRegistrationApplications.*.validityDate
              outJsonPath: $.Data.validityDate
            - inJsonPath: $.PetRegistrationApplications.*.status
              outJsonPath: $.Data.status
            - inJsonPath: $.PetRegistrationApplications.*.expireFlag
              outJsonPath: $.Data.expireFlag
            - inJsonPath: $.PetRegistrationApplications.*.petToken
              outJsonPath: $.Data.petToken
            - inJsonPath: $.PetRegistrationApplications.*.previousApplicationNumber
              outJsonPath: $.Data.previousApplicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.propertyId
              outJsonPath: $.Data.propertyId
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy
              outJsonPath: $.Data.lastmodifiedby
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime
              outJsonPath: $.Data.lastmodifiedtime
            - inJsonPath: $.PetRegistrationApplications.*.address
              outJsonPath: $.Data.address
            - inJsonPath: $.PetRegistrationApplications.*.petDetails
              outJsonPath: $.Data.petDetails
            - inJsonPath: $.PetRegistrationApplications.*.documents
              outJsonPath: $.Data.documents

    - topic: expire-ptr-application
      configKey: INDEX
      indexes:
        - name: ptr-application-expire-index
          type: general
          id: $.id, $.tenantId
          isBulk: false
          timeStampField: $.auditDetails.lastModifiedTime
          jsonPath: $.PetRegistrationApplications.*
          customJsonMapping:
            indexMapping: {"Data":{"id":"id","applicationNumber":"applicationNumber","status":"status",
                                   "lastmodifiedby":"lastmodifiedby","lastmodifiedtime":"lastmodifiedtime"}}
          fieldMapping:
            - inJsonPath: $.PetRegistrationApplications.*.id
              outJsonPath: $.Data.id
            - inJsonPath: $.PetRegistrationApplications.*.applicationNumber
              outJsonPath: $.Data.applicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.status
              outJsonPath: $.Data.status
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy
              outJsonPath: $.Data.lastmodifiedby
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime
              outJsonPath: $.Data.lastmodifiedtime

    - topic: renew-ptr-application
      configKey: INDEX
      indexes:
        - name: ptr-application-renew-index
          type: general
          id: $.id
          isBulk: true
          timeStampField: $.auditDetails.createdTime
          jsonPath: $.PetRegistrationApplications.*
          customJsonMapping:
            indexMapping: {"Data":{"id":"id","tenantId":"tenantId","applicationNumber":"applicationNumber",
                                   "applicantName":"applicantName","fatherName":"fatherName","mobileNumber":"mobileNumber",
                                   "emailId":"emailId","applicationType":"applicationType","validityDate":"validityDate",
                                   "status":"status","expireFlag":"expireFlag","petToken":"petToken","previousApplicationNumber":"previousApplicationNumber",
                                   "propertyId":"propertyId","createdby":"createdby","lastmodifiedby":"lastmodifiedby",
                                   "createdtime":"createdtime","lastmodifiedtime":"lastmodifiedtime","address":{},"petDetails":{},"documents":[]}}
          fieldMapping:
            - inJsonPath: $.PetRegistrationApplications.*.id
              outJsonPath: $.Data.id
            - inJsonPath: $.PetRegistrationApplications.*.tenantId
              outJsonPath: $.Data.tenantId
            - inJsonPath: $.PetRegistrationApplications.*.applicationNumber
              outJsonPath: $.Data.applicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.applicantName
              outJsonPath: $.Data.applicantName
            - inJsonPath: $.PetRegistrationApplications.*.fatherName
              outJsonPath: $.Data.fatherName
            - inJsonPath: $.PetRegistrationApplications.*.mobileNumber
              outJsonPath: $.Data.mobileNumber
            - inJsonPath: $.PetRegistrationApplications.*.emailId
              outJsonPath: $.Data.emailId
            - inJsonPath: $.PetRegistrationApplications.*.applicationType
              outJsonPath: $.Data.applicationType
            - inJsonPath: $.PetRegistrationApplications.*.validityDate
              outJsonPath: $.Data.validityDate
            - inJsonPath: $.PetRegistrationApplications.*.status
              outJsonPath: $.Data.status
            - inJsonPath: $.PetRegistrationApplications.*.expireFlag
              outJsonPath: $.Data.expireFlag
            - inJsonPath: $.PetRegistrationApplications.*.petToken
              outJsonPath: $.Data.petToken
            - inJsonPath: $.PetRegistrationApplications.*.previousApplicationNumber
              outJsonPath: $.Data.previousApplicationNumber
            - inJsonPath: $.PetRegistrationApplications.*.propertyId
              outJsonPath: $.Data.propertyId
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.createdBy
              outJsonPath: $.Data.createdby
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy
              outJsonPath: $.Data.lastmodifiedby
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.createdTime
              outJsonPath: $.Data.createdtime
            - inJsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime
              outJsonPath: $.Data.lastmodifiedtime
            - inJsonPath: $.PetRegistrationApplications.*.address
              outJsonPath: $.Data.address
            - inJsonPath: $.PetRegistrationApplications.*.petDetails
              outJsonPath: $.Data.petDetails
            - inJsonPath: $.PetRegistrationApplications.*.documents
              outJsonPath: $.Data.documents
